// Canonical route and speed data. All study modes derive from this file.
export const ROUTE_DATA_VERSION = '2.4.1';

export const TRACK_SPEED_DATA = {
  seaford_down: [
    {km:0.000, label:'Adelaide', speed:15, comment:'No permanent speed sign at 0.000'},
    {km:null, label:null, speed:35, comment:'At the end of the platform'},
    {km:0.872, label:null, speed:60, comment:null},
    {km:1.975, label:'Mile End', speed:null, comment:null},
    {km:2.121, label:null, speed:110, comment:null},
    {km:4.116, label:'Adelaide Showground', speed:null, comment:null},
    {km:4.196, label:null, speed:80, comment:null},
    {km:4.630, label:null, speed:60, comment:null},
    {km:4.945, label:'Goodwood', speed:null, comment:null},
    {km:5.714, label:null, speed:90, comment:null},
    {km:6.308, label:'Clarence Park', speed:null, comment:null},
    {km:7.138, label:'Emerson', speed:null, comment:null},
    {km:7.178, label:null, speed:70, comment:null},
    {km:7.850, label:'Edwardstown', speed:null, comment:null},
    {km:8.091, label:null, speed:50, comment:null},
    {km:8.235, label:null, speed:70, comment:null},
    {km:8.364, label:null, speed:110, comment:null},
    {km:9.115, label:'Woodlands Park', speed:null, comment:null},
    {km:10.094, label:null, speed:90, comment:null},
    {km:10.176, label:'Ascot Park', speed:null, comment:null},
    {km:11.240, label:null, speed:110, comment:null},
    {km:11.380, label:'Marion', speed:null, comment:null},
    {km:12.392, label:null, speed:90, comment:null},
    {km:12.861, label:null, speed:60, comment:null},
    {km:12.944, label:'Oaklands', speed:null, comment:null},
    {km:13.455, label:null, speed:100, comment:null},
    {km:13.703, label:'Warradale', speed:null, comment:null},
    {km:14.589, label:null, speed:55, comment:null},
    {km:14.613, label:'Hove', speed:null, comment:null},
    {km:15.840, label:'Brighton', speed:null, comment:null},
    {km:16.279, label:null, speed:80, comment:null},
    {km:16.920, label:'Seacliff Up', speed:null, comment:null},
    {km:17.105, label:'Seacliff Down', speed:null, comment:null},
    {km:18.039, label:null, speed:100, comment:null},
    {km:18.292, label:'Marino', speed:null, comment:null},
    {km:18.915, label:'Marino Rocks', speed:null, comment:null},
    {km:21.391, label:'Hallett Cove', speed:null, comment:null},
    {km:22.972, label:'Hallett Cove Beach', speed:null, comment:null},
    {km:23.293, label:null, speed:85, comment:null},
    {km:23.633, label:null, speed:100, comment:null},
    {km:25.248, label:null, speed:70, comment:null},
    {km:26.068, label:null, speed:100, comment:null},
    {km:26.345, label:null, speed:110, comment:null},
    {km:26.648, label:'Lonsdale', speed:null, comment:null},
    {km:28.704, label:null, speed:85, comment:null},
    {km:28.900, label:'Christie Downs', speed:null, comment:null},
    {km:29.030, label:null, speed:110, comment:null},
    {km:29.980, label:null, speed:70, comment:null},
    {km:30.208, label:'Noarlunga Centre', speed:null, comment:null},
    {km:30.350, label:null, speed:110, comment:null},
    {km:34.483, label:null, speed:100, comment:null},
    {km:34.562, label:'Seaford Meadows', speed:null, comment:null},
    {km:35.453, label:null, speed:70, comment:null},
    {km:35.667, label:null, speed:25, comment:null},
    {km:35.784, label:'Seaford', speed:null, comment:null},
    {km:35.943, label:'End of Seaford Line', speed:null, comment:null},
  ],
  seaford_up: [
    {km:35.943, label:'End of Seaford Line', speed:null, comment:null},
    {km:35.784, label:'Seaford', speed:null, comment:null},
    {km:35.784, label:null, speed:70, comment:null},
    {km:35.453, label:null, speed:100, comment:null},
    {km:34.562, label:'Seaford Meadows', speed:null, comment:null},
    {km:34.483, label:null, speed:110, comment:null},
    {km:30.350, label:null, speed:70, comment:null},
    {km:30.208, label:'Noarlunga Centre', speed:null, comment:null},
    {km:28.900, label:'Christie Downs', speed:null, comment:null},
    {km:28.826, label:null, speed:110, comment:null},
    {km:26.648, label:'Lonsdale', speed:null, comment:null},
    {km:26.314, label:null, speed:100, comment:null},
    {km:23.656, label:null, speed:85, comment:null},
    {km:23.323, label:null, speed:100, comment:null},
    {km:22.972, label:'Hallett Cove Beach', speed:null, comment:null},
    {km:21.391, label:'Hallett Cove', speed:null, comment:null},
    {km:19.053, label:null, speed:70, comment:null},
    {km:18.915, label:'Marino Rocks', speed:null, comment:null},
    {km:18.815, label:null, speed:80, comment:null},
    {km:18.292, label:'Marino', speed:null, comment:null},
    {km:17.651, label:null, speed:110, comment:null},
    {km:17.105, label:'Seacliff Down', speed:null, comment:null},
    {km:16.920, label:'Seacliff Up', speed:null, comment:null},
    {km:16.604, label:null, speed:60, comment:null},
    {km:15.840, label:'Brighton', speed:null, comment:null},
    {km:15.405, label:null, speed:45, comment:null},
    {km:14.613, label:'Hove', speed:null, comment:null},
    {km:14.530, label:null, speed:100, comment:null},
    {km:13.703, label:'Warradale', speed:null, comment:null},
    {km:13.424, label:null, speed:60, comment:null},
    {km:12.944, label:'Oaklands', speed:null, comment:null},
    {km:12.862, label:null, speed:90, comment:null},
    {km:12.394, label:null, speed:110, comment:null},
    {km:11.380, label:'Marion', speed:null, comment:null},
    {km:11.291, label:null, speed:90, comment:null},
    {km:10.176, label:'Ascot Park', speed:null, comment:null},
    {km:9.980, label:null, speed:80, comment:null},
    {km:9.115, label:'Woodlands Park', speed:null, comment:null},
    {km:8.364, label:null, speed:40, comment:null},
    {km:8.047, label:null, speed:75, comment:null},
    {km:7.850, label:'Edwardstown', speed:null, comment:null},
    {km:7.130, label:'Emerson', speed:null, comment:null},
    {km:6.973, label:null, speed:90, comment:null},
    {km:6.308, label:'Clarence Park', speed:null, comment:null},
    {km:5.708, label:null, speed:60, comment:null},
    {km:4.945, label:'Goodwood', speed:null, comment:null},
    {km:4.630, label:null, speed:80, comment:null},
    {km:4.116, label:'Adelaide Showground', speed:null, comment:null},
    {km:4.036, label:null, speed:110, comment:null},
    {km:1.975, label:'Mile End', speed:null, comment:null},
    {km:1.922, label:null, speed:80, comment:null},
    {km:1.160, label:null, speed:60, comment:null},
    {km:0.872, label:null, speed:35, comment:null},
    {km:0.000, label:'Adelaide', speed:15, comment:'Into Platform'},
    {km:null, label:null, speed:5, comment:'Prior to buffer'},
  ],
  belair_down: [
    {km:0, label:'Adelaide Station', speed:15, comment:'No permanent speed sign at 0.000'},
    {km:null, label:null, speed:35, comment:'Once past end of the platform'},
    {km:0.872, label:null, speed:55, comment:null},
    {km:1.13, label:null, speed:85, comment:null},
    {km:1.975, label:'Mile End', speed:null, comment:null},
    {km:2.078, label:null, speed:110, comment:null},
    {km:3, label:null, speed:90, comment:null},
    {km:3.972, label:null, speed:35, comment:null},
    {km:4.034, label:null, speed:60, comment:null},
    {km:4.116, label:'Adelaide Showground', speed:null, comment:null},
    {km:4.945, label:'Goodwood', speed:null, comment:null},
    {km:5.137, label:'Millswood Loop', speed:null, comment:null},
    {km:5.74, label:null, speed:90, comment:null},
    {km:5.953, label:'Millswood', speed:null, comment:null},
    {km:6.967, label:'Unley Park', speed:null, comment:null},
    {km:8.533, label:'Mitcham', speed:null, comment:null},
    {km:8.635, label:null, speed:55, comment:null},
    {km:8.86, label:null, speed:90, comment:null},
    {km:9.3, label:'Torrens Park', speed:null, comment:null},
    {km:10.71, label:'Lynton', speed:null, comment:null},
    {km:11.157, label:null, speed:65, comment:null},
    {km:11.299, label:'Sleeps Hill Loop', speed:null, comment:null},
    {km:11.765, label:null, speed:55, comment:null},
    {km:12.051, label:null, speed:90, comment:null},
    {km:12.072, label:'Sleeps Hill Tunnel Adelaide End', speed:null, comment:null},
    {km:12.805, label:'Sleeps Hill Tunnel Belair End', speed:null, comment:null},
    {km:12.825, label:null, speed:50, comment:null},
    {km:13.483, label:null, speed:40, comment:null},
    {km:14.158, label:'Eden Hills', speed:null, comment:null},
    {km:14.303, label:null, speed:50, comment:null},
    {km:14.9, label:'Shepherds Hill Tunnel Adelaide End', speed:null, comment:null},
    {km:15.037, label:'Shepherds Hill Tunnel Belair End', speed:null, comment:null},
    {km:15.053, label:'Eden Hills Loop', speed:null, comment:null},
    {km:15.281, label:null, speed:40, comment:null},
    {km:15.686, label:null, speed:50, comment:null},
    {km:17.241, label:'Coromandel', speed:null, comment:null},
    {km:17.5, label:null, speed:40, comment:'Signal Sighting'},
    {km:17.74, label:null, speed:35, comment:null},
    {km:18.111, label:'Blackwood', speed:null, comment:null},
    {km:18.259, label:null, speed:45, comment:null},
    {km:18.453, label:null, speed:55, comment:null},
    {km:19.319, label:'Glenalta', speed:null, comment:null},
    {km:20.168, label:null, speed:40, comment:null},
    {km:20.56, label:'Pinera', speed:null, comment:null},
    {km:21.27, label:null, speed:35, comment:null},
    {km:21.51, label:'Belair', speed:null, comment:null},
    {km:21.748, label:'End of Belair Line', speed:null, comment:null},
  ],
  belair_up: [
    {km:21.748, label:'End of Belair Line', speed:null, comment:null},
    {km:21.51, label:'Belair', speed:null, comment:null},
    {km:21.39, label:null, speed:35, comment:null},
    {km:21.27, label:null, speed:40, comment:null},
    {km:20.56, label:'Pinera', speed:null, comment:null},
    {km:20.168, label:null, speed:55, comment:null},
    {km:19.319, label:'Glenalta', speed:null, comment:null},
    {km:18.453, label:null, speed:45, comment:null},
    {km:18.259, label:null, speed:35, comment:null},
    {km:18.111, label:'Blackwood', speed:null, comment:null},
    {km:17.74, label:null, speed:50, comment:null},
    {km:17.241, label:'Coromandel', speed:null, comment:null},
    {km:15.686, label:null, speed:40, comment:null},
    {km:15.281, label:null, speed:50, comment:null},
    {km:15.266, label:'Eden Hills Loop', speed:null, comment:null},
    {km:15.037, label:'Shepherds Hill Tunnel Belair End', speed:null, comment:null},
    {km:14.9, label:'Shepherds Hill Tunnel Adelaide End', speed:null, comment:null},
    {km:14.303, label:null, speed:40, comment:null},
    {km:14.158, label:'Eden Hills', speed:null, comment:null},
    {km:13.483, label:null, speed:50, comment:null},
    {km:12.825, label:null, speed:90, comment:null},
    {km:12.805, label:'Sleeps Hill Tunnel Belair End', speed:null, comment:null},
    {km:12.072, label:'Sleeps Hill Tunnel Adelaide End', speed:null, comment:null},
    {km:12.051, label:null, speed:55, comment:null},
      {km:11.765, label:null, speed:65, comment:null},
      {km:11.577, label:'Sleeps Hill Loop', speed:null, comment:null},
    {km:11.157, label:null, speed:90, comment:null},
    {km:10.71, label:'Lynton', speed:null, comment:null},
    {km:9.3, label:'Torrens Park', speed:null, comment:null},
    {km:8.86, label:null, speed:55, comment:null},
    {km:8.635, label:null, speed:90, comment:null},
    {km:8.533, label:'Mitcham', speed:null, comment:null},
    {km:6.967, label:'Unley Park', speed:null, comment:null},
    {km:5.953, label:'Millswood', speed:null, comment:null},
    {km:5.74, label:null, speed:60, comment:null},
    {km:5.617, label:'Millswood Loop', speed:null, comment:null},
    {km:4.945, label:'Goodwood', speed:null, comment:null},
    {km:4.63, label:null, speed:80, comment:null},
    {km:4.116, label:'Adelaide Showground', speed:null, comment:null},
    {km:3.731, label:null, speed:110, comment:null},
    {km:1.975, label:'Mile End', speed:null, comment:null},
    {km:1.922, label:null, speed:85, comment:null},
    {km:1.132, label:null, speed:55, comment:null},
    {km:0.872, label:null, speed:35, comment:null},
    {km:0, label:'Adelaide Station', speed:15, comment:'Into Platform'},
    {km:null, label:null, speed:5, comment:'Just prior to buffer'},
  ],
  outerharbor_down: [
    {km:0, label:'Adelaide', speed:15, comment:'No permanent speed sign at 0.000'},
    {km:null, label:null, speed:35, comment:'Once past end of the platform'},
    {km:0.633, label:null, speed:70, comment:null},
    {km:1.515, label:null, speed:90, comment:null},
    {km:2.5, label:'Bowden', speed:null, comment:null},
    {km:4.19, label:'Croydon', speed:null, comment:null},
    {km:5.054, label:'West Croydon', speed:null, comment:null},
    {km:5.965, label:'Kilkenny', speed:null, comment:null},
    {km:6.05, label:null, speed:80, comment:null},
    {km:6.774, label:'Woodville Park', speed:null, comment:null},
    {km:7.307, label:null, speed:90, comment:null},
    {km:7.465, label:'Woodville', speed:null, comment:null},
    {km:8.485, label:'St Clair', speed:null, comment:null},
    {km:9.168, label:'Cheltenham', speed:null, comment:null},
    {km:10.14, label:null, speed:40, comment:'Non-conforming track centres through Alberton Station'},
    {km:10.21, label:'Alberton', speed:null, comment:null},
    {km:10.28, label:null, speed:90, comment:null},
    {km:10.79, label:null, speed:80, comment:null},
    {km:11.023, label:null, speed:70, comment:null},
    {km:11.189, label:null, speed:40, comment:null},
    {km:11.676, label:'Port Adelaide', speed:null, comment:null},
    {km:11.972, label:null, speed:90, comment:null},
    {km:12.48, label:null, speed:40, comment:null},
    {km:13.076, label:'Ethelton', speed:null, comment:null},
    {km:13.132, label:null, speed:50, comment:null},
    {km:13.767, label:'Glanville', speed:null, comment:null},
    {km:13.97, label:null, speed:65, comment:null},
    {km:14.632, label:'Peterhead', speed:null, comment:null},
    {km:15.474, label:'Largs', speed:null, comment:null},
    {km:16.387, label:'Largs North', speed:null, comment:null},
    {km:17.166, label:'Draper', speed:null, comment:null},
    {km:17.324, label:null, speed:80, comment:null},
    {km:17.96, label:null, speed:65, comment:null},
    {km:18.139, label:'Taperoo', speed:null, comment:null},
    {km:18.302, label:null, speed:80, comment:null},
    {km:18.81, label:'Midlunga', speed:null, comment:null},
    {km:19.55, label:'Osborne', speed:null, comment:null},
    {km:19.616, label:null, speed:65, comment:null},
    {km:20.46, label:'North Haven', speed:null, comment:null},
    {km:20.796, label:null, speed:50, comment:null},
    {km:21.926, label:'Outer Harbor', speed:null, comment:null},
    {km:21.975, label:'End of Outer Harbor Line', speed:null, comment:null},
  ],
  outerharbor_up: [
    {km:21.975, label:'End of Outer Harbor Line', speed:null, comment:null},
    {km:21.926, label:'Outer Harbor', speed:null, comment:null},
    {km:21.926, label:null, speed:50, comment:null},
    {km:20.796, label:null, speed:65, comment:null},
    {km:20.46, label:'North Haven', speed:null, comment:null},
    {km:19.616, label:null, speed:80, comment:null},
    {km:19.55, label:'Osborne', speed:null, comment:null},
    {km:18.81, label:'Midlunga', speed:null, comment:null},
    {km:18.302, label:null, speed:65, comment:null},
    {km:18.139, label:'Taperoo', speed:null, comment:null},
    {km:17.96, label:null, speed:80, comment:null},
    {km:17.324, label:null, speed:65, comment:null},
    {km:17.166, label:'Draper', speed:null, comment:null},
    {km:16.387, label:'Largs North', speed:null, comment:null},
    {km:15.474, label:'Largs', speed:null, comment:null},
    {km:14.632, label:'Peterhead', speed:null, comment:null},
    {km:13.769, label:'Glanville', speed:null, comment:null},
    {km:13.643, label:null, speed:35, comment:null},
    {km:13.544, label:null, speed:50, comment:null},
    {km:13.132, label:null, speed:40, comment:null},
    {km:13.076, label:'Ethelton', speed:null, comment:null},
    {km:12.478, label:null, speed:90, comment:null},
    {km:11.972, label:null, speed:40, comment:null},
    {km:11.676, label:'Port Adelaide', speed:null, comment:null},
    {km:11.146, label:null, speed:70, comment:null},
    {km:11.023, label:null, speed:80, comment:null},
    {km:10.804, label:null, speed:90, comment:null},
    {km:10.28, label:null, speed:40, comment:'Non-conforming track centres through Alberton Station'},
    {km:10.21, label:'Alberton', speed:null, comment:null},
    {km:10.14, label:null, speed:90, comment:null},
    {km:9.168, label:'Cheltenham', speed:null, comment:null},
    {km:8.485, label:'St Clair', speed:null, comment:null},
    {km:7.456, label:'Woodville', speed:null, comment:null},
    {km:7.347, label:null, speed:70, comment:null},
    {km:6.774, label:'Woodville Park', speed:null, comment:null},
    {km:5.965, label:'Kilkenny', speed:null, comment:null},
    {km:5.788, label:null, speed:90, comment:null},
    {km:5.054, label:'West Croydon', speed:null, comment:null},
    {km:4.19, label:'Croydon', speed:null, comment:null},
    {km:2.5, label:'Bowden', speed:null, comment:null},
    {km:1.515, label:null, speed:70, comment:null},
    {km:0.633, label:null, speed:35, comment:null},
    {km:0, label:'Adelaide', speed:15, comment:'Into Platform'},
    {km:null, label:null, speed:5, comment:'Prior to buffer stop'},
  ],
  gawler_down: [
    {km:0, label:'Adelaide Station', speed:15, comment:'No permanent speed sign at 0.000'},
    {km:null, label:null, speed:35, comment:'At the end of the platform'},
    {km:0.633, label:null, speed:70, comment:null},
    {km:1.515, label:null, speed:75, comment:null},
    {km:2.4, label:null, speed:110, comment:null},
    {km:2.497, label:'North Adelaide', speed:null, comment:null},
    {km:3.461, label:null, speed:80, comment:null},
    {km:3.65, label:'Ovingham', speed:null, comment:null},
    {km:4.07, label:null, speed:110, comment:null},
    {km:4.899, label:'Dudley Park', speed:null, comment:null},
    {km:5.52, label:null, speed:80, comment:null},
    {km:6.008, label:'Islington', speed:null, comment:null},
    {km:6.083, label:null, speed:110, comment:null},
    {km:7.659, label:null, speed:70, comment:null},
    {km:7.69, label:null, speed:85, comment:null},
    {km:7.744, label:null, speed:105, comment:null},
    {km:7.807, label:'Kilburn', speed:null, comment:null},
    {km:8.615, label:null, speed:110, comment:null},
    {km:10.529, label:null, speed:100, comment:null},
    {km:10.613, label:'Dry Creek', speed:null, comment:null},
    {km:10.83, label:null, speed:110, comment:null},
    {km:14.846, label:'Mawson Lakes', speed:null, comment:null},
    {km:15.573, label:'Greenfields', speed:null, comment:null},
    {km:16.567, label:'Parafield Gardens', speed:null, comment:null},
    {km:17.704, label:'Parafield', speed:null, comment:null},
    {km:19.919, label:'Chidda', speed:null, comment:null},
    {km:19.919, label:null, speed:70, comment:null},
    {km:20.238, label:'Salisbury', speed:null, comment:null},
    {km:20.74, label:'Salisbury Siding', speed:null, comment:'15 km/h into Salisbury Siding'},
    {km:21.251, label:null, speed:110, comment:null},
    {km:21.779, label:'Nurlutta', speed:null, comment:null},
    {km:24.032, label:'Elizabeth South', speed:null, comment:null},
    {km:25.716, label:'Elizabeth', speed:null, comment:null},
    {km:26.001, label:'Elizabeth Siding', speed:null, comment:null},
    {km:27.169, label:null, speed:85, comment:null},
    {km:27.3, label:'Womma', speed:null, comment:null},
    {km:27.515, label:null, speed:110, comment:null},
    {km:28.324, label:'Broadmeadows', speed:null, comment:null},
    {km:30.223, label:'Smithfield', speed:null, comment:null},
    {km:30.254, label:null, speed:100, comment:null},
    {km:31.047, label:null, speed:110, comment:null},
    {km:32.02, label:'Munno Para', speed:null, comment:null},
    {km:34.099, label:'Kudla', speed:null, comment:null},
    {km:37.226, label:'Tamblin', speed:null, comment:null},
    {km:38.27, label:'Evanston', speed:null, comment:null},
    {km:38.848, label:null, speed:50, comment:null},
    {km:39.315, label:'Gawler Racecourse', speed:null, comment:null},
      {km:39.789, label:'Gawler Platforms 1 & 2', speed:30, comment:'Only through Platforms 1 & 2'},
    {km:39.847, label:'Gawler Platform 3', speed:null, comment:null},
    {km:39.85, label:null, speed:20, comment:null},
    {km:39.94, label:null, speed:50, comment:null},
    {km:41.43, label:'Gawler Oval', speed:null, comment:null},
    {km:42.154, label:'Gawler Central', speed:null, comment:null},
    {km:42.183, label:'End of Gawler Line', speed:null, comment:'Buffer placed prior to Murray St'},
  ],
  gawler_up: [
    {km:42.183, label:'End of Gawler Line', speed:25, comment:'Reduced functionality ATP signal 4272'},
    {km:41.997, label:'Gawler Central', speed:50, comment:null},
    {km:41.430, label:'Gawler Oval', speed:null, comment:null},
    {km:39.940, label:null, speed:20, comment:'This speed is also posted for down movements as well as the back road.'},
    {km:39.847, label:'Gawler Platform 3', speed:null, comment:null},
    {km:39.789, label:null, speed:50, comment:null},
    {km:39.789, label:'Gawler Platforms 1 & 2', speed:30, comment:'Only through Platforms 1 & 2'},
    {km:39.620, label:null, speed:50, comment:null},
    {km:39.315, label:'Gawler Racecourse', speed:null, comment:null},
    {km:39.032, label:null, speed:100, comment:null},
    {km:38.27, label:'Evanston', speed:null, comment:null},
    {km:38.176, label:null, speed:110, comment:null},
    {km:37.226, label:'Tamblin', speed:null, comment:null},
    {km:34.099, label:'Kudla', speed:null, comment:null},
    {km:33.927, label:null, speed:105, comment:null},
    {km:33.713, label:null, speed:110, comment:null},
    {km:32.02, label:'Munno Para', speed:null, comment:null},
    {km:30.223, label:'Smithfield', speed:null, comment:null},
    {km:28.324, label:'Broadmeadows', speed:null, comment:null},
    {km:28.119, label:null, speed:100, comment:null},
    {km:27.3, label:'Womma', speed:null, comment:null},
    {km:27.186, label:null, speed:110, comment:null},
    {km:26.402, label:'Elizabeth Siding', speed:null, comment:null},
    {km:25.716, label:'Elizabeth', speed:null, comment:null},
    {km:24.032, label:'Elizabeth South', speed:null, comment:null},
    {km:21.527, label:'Nurlutta', speed:null, comment:null},
    {km:20.726, label:null, speed:70, comment:null},
    {km:20.238, label:'Salisbury', speed:null, comment:null},
    {km:19.915, label:null, speed:110, comment:null},
    {km:18.85, label:'Chidda', speed:null, comment:null},
    {km:17.704, label:'Parafield', speed:null, comment:null},
    {km:16.567, label:'Parafield Gardens', speed:null, comment:null},
    {km:15.573, label:'Greenfields', speed:null, comment:null},
    {km:14.846, label:'Mawson Lakes', speed:null, comment:null},
    {km:10.613, label:'Dry Creek', speed:null, comment:null},
    {km:9.97, label:null, speed:100, comment:null},
    {km:9.493, label:null, speed:110, comment:null},
    {km:8.614, label:null, speed:90, comment:null},
    {km:7.678, label:'Kilburn', speed:null, comment:null},
    {km:7.597, label:null, speed:110, comment:null},
    {km:6.063, label:null, speed:80, comment:null},
    {km:6.008, label:'Islington', speed:null, comment:null},
    {km:5.52, label:null, speed:110, comment:null},
    {km:4.899, label:'Dudley Park', speed:null, comment:null},
    {km:4.07, label:null, speed:80, comment:null},
    {km:3.65, label:'Ovingham', speed:null, comment:null},
    {km:3.461, label:null, speed:110, comment:null},
    {km:2.497, label:'North Adelaide', speed:null, comment:null},
    {km:2.384, label:null, speed:75, comment:null},
    {km:1.515, label:null, speed:70, comment:null},
    {km:0.633, label:'Adelaide Yard', speed:35, comment:null},
    {km:0, label:'Adelaide Station', speed:15, comment:'Into Platform'},
    {km:null, label:null, speed:5, comment:'Before buffer'},
  ],
};

// Flinders branches off the Seaford mainline between Woodlands Park and Ascot Park.
// The Flinders addenda only documents kilometrage from that junction outward, on the
// same absolute Adelaide-based km scale as Seaford. So the full Down/Up picture is
// built by splicing Seaford's trunk portion together with Flinders' own branch data.
const FLINDERS_OWN_DOWN = [
  {km:9.996, label:'Points TJ1', speed:null, comment:null},
  {km:10.011, label:'Points TJ2', speed:null, comment:null},
  {km:10.039, label:null, speed:40, comment:null},
  {km:10.278, label:null, speed:90, comment:null},
  {km:11.180, label:null, speed:70, comment:null},
  {km:11.442, label:'Mitchell Park', speed:null, comment:null},
  {km:11.610, label:null, speed:80, comment:null},
  {km:12.182, label:null, speed:70, comment:null},
  {km:12.240, label:'Tonsley', speed:null, comment:null},
  {km:12.925, label:null, speed:50, comment:null},
  {km:13.583, label:null, speed:15, comment:null},
  {km:13.590, label:'Flinders', speed:null, comment:null},
  {km:13.755, label:'Buffer Stop', speed:null, comment:null},
  {km:13.770, label:'End of Flinders Line', speed:null, comment:null},
];
const FLINDERS_OWN_UP = [
  {km:13.770, label:'End of Flinders Line', speed:null, comment:null},
  {km:13.755, label:'Buffer Stop', speed:null, comment:null},
  {km:13.590, label:'Flinders', speed:null, comment:null},
  {km:13.583, label:null, speed:50, comment:null},
  {km:12.925, label:null, speed:70, comment:null},
  {km:12.240, label:'Tonsley', speed:null, comment:null},
  {km:12.182, label:null, speed:80, comment:null},
  {km:11.610, label:null, speed:45, comment:null},
  {km:11.566, label:'Mitchell Park', speed:null, comment:null},
  {km:11.180, label:null, speed:35, comment:'No board placed due to turnout'},
  {km:11.066, label:null, speed:90, comment:null},
  {km:10.278, label:null, speed:35, comment:'No board placed due to turnout'},
];

(function buildFlindersTrackSpeeds(){
  const trunkDown = TRACK_SPEED_DATA.seaford_down;
  const wpIdx = trunkDown.findIndex(r => r.label === 'Woodlands Park');
  const trunkDownPortion = wpIdx >= 0 ? trunkDown.slice(0, wpIdx + 1) : [];
  TRACK_SPEED_DATA.tonsley_down = trunkDownPortion.concat(FLINDERS_OWN_DOWN);

  const trunkUp = TRACK_SPEED_DATA.seaford_up;
  const rejoinIdx = trunkUp.findIndex(r => r.km === 9.980 && r.speed === 80);
  const trunkUpPortion = rejoinIdx >= 0 ? trunkUp.slice(rejoinIdx) : [];
  TRACK_SPEED_DATA.tonsley_up = FLINDERS_OWN_UP.concat(trunkUpPortion);
})();

// Grange branches off Outer Harbor at Woodville; Port Dock branches off Outer Harbor
// just past Alberton. Both addenda only document kilometrage from their own junction
// outward, on the same absolute Adelaide-based km scale as Outer Harbor, so both are
// built by splicing Outer Harbor's trunk portion together with each branch's own data.
const GRANGE_OWN_DOWN = [
  {km:7.252, label:'Point WV1', speed:null, comment:null},
  {km:7.324, label:'Point WV2', speed:null, comment:null},
  {km:7.325, label:null, speed:35, comment:'No speed board at 7.325'},
  {km:7.481, label:'Woodville', speed:null, comment:null},
  {km:7.494, label:null, speed:35, comment:'Additional 35km/h speed board at 7.494'},
  {km:8.235, label:null, speed:40, comment:null},
  {km:8.326, label:null, speed:80, comment:null},
  {km:9.080, label:'Albert Park', speed:null, comment:null},
  {km:10.311, label:'Seaton Park', speed:null, comment:null},
  {km:10.559, label:null, speed:55, comment:null},
  {km:11.679, label:null, speed:80, comment:null},
  {km:11.969, label:'East Grange', speed:null, comment:null},
  {km:12.759, label:null, speed:10, comment:'10 km/h until buffer'},
  {km:12.962, label:'Grange', speed:null, comment:null},
  {km:13.007, label:'End of Grange Line', speed:null, comment:null},
];
const GRANGE_OWN_UP = [
  {km:13.007, label:'End of Line', speed:null, comment:null},
  {km:13.000, label:null, speed:25, comment:'No speed board at 13.000. Additional 25km/h speed board at 12.880'},
  {km:12.962, label:'Grange', speed:null, comment:null},
  {km:12.840, label:null, speed:10, comment:null},
  {km:12.759, label:null, speed:80, comment:null},
  {km:11.969, label:'East Grange', speed:null, comment:null},
  {km:11.679, label:null, speed:55, comment:null},
  {km:10.559, label:null, speed:80, comment:null},
  {km:10.311, label:'Seaton Park', speed:null, comment:null},
  {km:9.080, label:'Albert Park', speed:null, comment:null},
  {km:8.705, label:null, speed:50, comment:null},
  {km:8.326, label:null, speed:40, comment:null},
  {km:7.481, label:'Woodville', speed:null, comment:null},
];
const PORTDOCK_OWN_DOWN = [
  {km:10.712, label:'Point PA1A', speed:35, comment:null},
  {km:10.780, label:'Point PA1/Point PA2', speed:null, comment:null},
  {km:11.268, label:'Port Dock Loop', speed:null, comment:null},
  {km:11.834, label:'Port Dock', speed:null, comment:null},
  {km:null, label:null, speed:15, comment:'Arriving into Port Dock Platform'},
  {km:11.968, label:'End of Line', speed:null, comment:null},
];
const PORTDOCK_OWN_UP = [
  {km:11.968, label:'End of Line', speed:null, comment:null},
  {km:11.834, label:'Port Dock', speed:35, comment:'Departing from Port Dock Platform'},
  {km:11.268, label:'Port Dock Loop', speed:null, comment:null},
  {km:10.780, label:'Point PA2/Point PA1A', speed:null, comment:null},
];

(function buildGrangeAndPortDockTrackSpeeds(){
  const ohDown = TRACK_SPEED_DATA.outerharbor_down;
  const ohUp = TRACK_SPEED_DATA.outerharbor_up;

  const wpDownIdx = ohDown.findIndex(r => r.label === 'Woodville Park');
  TRACK_SPEED_DATA.grange_down = (wpDownIdx >= 0 ? ohDown.slice(0, wpDownIdx + 1) : []).concat(GRANGE_OWN_DOWN);

  // Grange Up uses its branch-specific addenda only as far as Woodville.
  // After Woodville the train is back on the shared Outer Harbor main line,
  // so inherit the Outer Harbor Up data from immediately AFTER Woodville.
  // This preserves the 70 km/h change at 7.347 km and the 90 km/h change at 5.788 km.
  const woodvilleUpIdx = ohUp.findIndex(r => r.label === 'Woodville');
  const grangeUpTail = woodvilleUpIdx >= 0 ? ohUp.slice(woodvilleUpIdx + 1) : [];
  TRACK_SPEED_DATA.grange_up = GRANGE_OWN_UP.concat(grangeUpTail);

  const pdDownIdx = ohDown.findIndex(r => r.km === 10.280 && r.speed === 90);
  TRACK_SPEED_DATA.portdock_down = (pdDownIdx >= 0 ? ohDown.slice(0, pdDownIdx + 1) : []).concat(PORTDOCK_OWN_DOWN);

  const pdUpIdx = ohUp.findIndex(r => r.km === 10.280 && r.speed === 40);
  TRACK_SPEED_DATA.portdock_up = PORTDOCK_OWN_UP.concat(pdUpIdx >= 0 ? ohUp.slice(pdUpIdx) : []);
})();

export const TRACK_SPEED_GROUPS = [
  { name:'Gawler Line', down:'gawler_down', up:'gawler_up', hue:'#e8636b' },
  { name:'Grange Line', down:'grange_down', up:'grange_up', hue:'#29c4e0' },
  { name:'Outer Harbor Line', down:'outerharbor_down', up:'outerharbor_up', hue:'#29c4e0' },
  { name:'Port Dock Line', down:'portdock_down', up:'portdock_up', hue:'#29c4e0' },
  { name:'Seaford Line', down:'seaford_down', up:'seaford_up', hue:'#e8a830' },
  { name:'Belair Line', down:'belair_down', up:'belair_up', hue:'#44b87f' },
  { name:'Flinders Line', down:'tonsley_down', up:'tonsley_up', hue:'#e8a830' },
];
